// THIS FILE IS AUTOGENERATED. DO NOT EDIT!

package maker

import "github.com/ethereum/go-ethereum/common"

// https://changelog.makerdao.com/releases/mainnet/1.0.3/contracts.json
var (
	DaiAddress      = common.HexToAddress("0x6B175474E89094C44Da98b954EedeAC495271d0F")
	FlapAddress     = common.HexToAddress("0xdfE0fb1bE2a52CDBf8FB962D5701d7fd0902db9f")
	FlipBatAAddress = common.HexToAddress("0xaA745404d55f88C108A28c86abE7b5A1E7817c07")
	FlipEthAAddress = common.HexToAddress("0xd8a04F5412223F513DC55F839574430f5EC15531")
	FlipSaiAddress  = common.HexToAddress("0x5432b2f3c0DFf95AA191C45E5cbd539E2820aE72")
	FlopAddress     = common.HexToAddress("0x4D95A049d5B0b7d32058cd3F2163015747522e99")
	JoinBatAAddress = common.HexToAddress("0x3D0B1912B66114d4096F48A8CEe3A56C231772cA")
	JoinEthAAddress = common.HexToAddress("0x2F0b23f53734252Bda2277357e97e1517d6B042A")
	JoinSaiAddress  = common.HexToAddress("0xad37fd42185Ba63009177058208dd1be4b136e6b")
	JugAddress      = common.HexToAddress("0x19c0976f590D67707E62397C87829d896Dc0f1F1")
	PotAddress      = common.HexToAddress("0x197E90f9FAD81970bA7976f33CbD77088E5D7cf7")
	VatAddress      = common.HexToAddress("0x35D1b3F3D7966A1DFe207aa4514C12a259A0492B")
	VowAddress      = common.HexToAddress("0xA950524441892A31ebddF91d3cEEFa04Bf454466")
)
